# Generated by Django 3.2.6 on 2021-08-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
