# Generated by Django 3.2.6 on 2021-08-31 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210831_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlistaccess',
            old_name='list_id',
            new_name='todo_list',
        ),
        migrations.RenameField(
            model_name='userlistaccess',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertasks',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='usertasks',
            old_name='user_id',
            new_name='user',
        ),
    ]
