# Generated by Django 3.2.6 on 2021-08-31 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210831_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userlistaccess',
            name='todo_list',
        ),
        migrations.RemoveField(
            model_name='userlistaccess',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertasks',
            name='task',
        ),
        migrations.RemoveField(
            model_name='usertasks',
            name='user',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
        migrations.DeleteModel(
            name='UserListAccess',
        ),
        migrations.DeleteModel(
            name='UserTasks',
        ),
    ]
