# Generated by Django 3.2.6 on 2021-09-02 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_alter_userrole_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='users_rel',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='task',
            name='from_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.todolist'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('todo_list', 'user')},
        ),
    ]
