# Generated by Django 3.2.6 on 2021-09-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='role',
            name='todo_list',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='from_list',
        ),
        migrations.RemoveField(
            model_name='task',
            name='users',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='users',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
